# action.yml
name: 'OTEL Collector Builder'
description: 'Use the OTEL Collector Builder in a Github Action'
inputs:
  collector_builder_version:
    description: 'Version of the collector builder to use'
    default: '0.84.0'
  output_dir:
    description: 'Path to the output directory of the finished binary'
    default: '_build/otelcollector'
  config_file:
    description: 'Path to the collector builder config file'
    required: true
    default: 'config.yaml'
outputs:
  collector_binary_path:
    description: 'Path to the finished binary, same as output_dir'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.output_dir }}
    - ${{ inputs.config_file }}
    - ${{ inputs.collector_builder_version }}
