dist:
  name: otelcol-custom
  description: Local OpenTelemetry Collector binary
  output_path: /tmp/dist
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/loggingexporter v0.85.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.85.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.85.0
