on: [push]

jobs:
  custom-collector-action:
    runs-on: ubuntu-latest
    name: A job to build a custom OpenTelemetry Collector
    steps:
      - uses: actions/checkout@v3
      - name: Custom Collector Step
        id: collector-build
        uses: jwafle/auto-collector-builder@main
        with:
          collector_builder_version: '0.84.0'
          config_file: 'test-config.yml'
      - name: Print the output location
        run: echo "The file is ${{ steps.collector-build.outputs.collector_binary_path }}"